- name: Установка Docker Ubuntu 22.04
  hosts: all
  become: true

  tasks:
    - name: Тест ping
      ping:

    - name: 1. Обновление cache
      apt:
        update_cache: yes

    - name: 2. Создание директории для GPG-ключей APT
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'
        owner: root
        group: root

    - name: 3. Скачивание GPG-ключа Docker
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'

    - name: 4. Получить архитектуру системы
      set_fact:
        deb_architecture: "{{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }}"

    - name: testing debug
      ansible.builtin.debug:
        msg:
        - "Архитектура ОС: {{ deb_architecture }}"
        - "Имя дистрибутива: {{ ansible_distribution_release }}"

    - name: 5. Добавить репозиторий Docker
      ansible.builtin.apt_repository:
        repo: "deb [arch={{ deb_architecture }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        filename: docker
        state: present

    - name: 6. Обновление cache
      apt:
        update_cache: yes

    - name: 7. Установка Docker
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
          - tree

    - name: testing debug
      ansible.builtin.debug:
        msg:
        - "Пользователь: {{ ansible_user }}"

    - name: 8. Проверка наличия группы docker
      ansible.builtin.group:
        name: docker
        state: present
      register: group_exist # Регистрация работы модуля

    - name: 9. Добавить текущего пользователя в группу docker
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes # аналог флага -a в системной команде usermod -aG
      # Добавление пользователя только, если группа docker существует
      when: group_exist is succeeded

    # перезапуск сессии для создания контейнеров от имени пользователя
    - name: 10. Обновить SSH-сессию, чтобы применить права групп
      ansible.builtin.meta: reset_connection

    - name: 11 Убедиться, что служба Docker запущена
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true
      become: true

    - name: 12. Создать директорию для проекта и назначить владельца
      ansible.builtin.file:
        path: /opt/application
        state: directory
        owner: "{{ ansible_user }}"
        group: docker
        mode: '0775'
      become: true

    - name: 13. Клонирование проекта из Git-репозитория
      ansible.builtin.git:
        repo: 'https://github.com/smyity/application.git' # ссылка на git репозиторий
        dest: /opt/application                            # директория на сервере
        version: main                                     # ветка
        force: true                                       # перезаписать локальные изменения, если они есть
      register: git_result                                # результат для отслеживания изменений
      become: false

    - name: 14 Узнать внешний IP-адрес хоста
      ansible.builtin.uri:
        url: https://ifconfig.me/ip
        return_content: true
      register: host_public_ip

    - name: 15. Изменение файла .env
      ansible.builtin.copy:
        content: |
          server_ip={{ host_public_ip.content | trim }}
          clickhouse_username={{ lookup('env', 'CH_USERNAME') }}
          clickhouse_password={{ lookup('env', 'CH_PASSWORD') }}
        dest: /opt/application/.env
        force: yes
        mode: '0600'

    # - name: 15.1 Изменение переменной ip адреса в .env файле
    #   ansible.builtin.lineinfile:
    #     path: /opt/application/.env
    #     regexp: '^server_ip='
    #     line: "server_ip={{ host_public_ip.content | trim }}"
    #     state: present

    - name: 16. Запуск Docker Compose проекта
      community.docker.docker_compose_v2:
        project_src: /opt/application         # путь до compose.yml
        state: present
        pull: always                          # скачивать новые образы, если они обновились
