name: Создание и удаление ВМ по записи в файле necessary_state.txt

on:
  push:
    branches:
      - main
    paths:
      - 'necessary_state.txt' # триггер запуска pipeline

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.A_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.S_KEY }}
      clickhouse_username: ${{ secrets.CH_USER }}
      clickhouse_password: ${{ secrets.CH_PASS }}
      YC_SERVICE_ACCOUNT_KEY_FILE: ${{ secrets.A_1 }}

    steps:
    - name: Загрузка кода репозитория в рабочую директорию виртуальной машины
      uses: actions/checkout@v4

    - name: Настройка Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.13.4"
        terraform_wrapper: false # отключение зависания логов

    - name: Инициализация Terraform (аналог "terraform init" на машине)
      run: terraform init

    - name: Чтение файла necessary_state.txt для получения желаемого состояноя ВМ
      id: check_state
      run: |
        # удаление пробелов и перевод в нижний регистр
        STATE=$(cat necessary_state.txt | tr -d '[:space:]' | tr '[:upper:]' '[:lower:]')
        echo "Существование ВМ: $STATE"
        echo "state=$STATE" >> $GITHUB_OUTPUT

    - name: Создание ВМ (yes)
      if: steps.check_state.outputs.state == 'yes'
      run: |
        eval $(ssh-agent -s)
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-add ~/.ssh/id_rsa
        terraform apply -auto-approve

    - name: Удаление ВМ (no)
      if: steps.check_state.outputs.state == 'no'
      run: terraform destroy -auto-approve

    - name: Неверная запись в файле necessary_state.txt
      if: steps.check_state.outputs.state != 'yes' && steps.check_state.outputs.state != 'no'
      run: |
        echo "[!] Запись в файле necessary_state.txt должна быть либо 'yes', либо 'no'."
        exit 1
